language: c

matrix:
  include:
    # Arm64 builds
    - name: "KEMs: ARM64 + GCC"
      os: linux
      arch: arm64
      compiler: gcc
      before_script:
      script:
        - travis_wait 60 docker run -e CI=true --rm -v ~/.ccache:/ccache -v `pwd`:`pwd` -w `pwd` "pqclean/ci-container:arm64" /bin/bash -c "
          uname -a &&
          export CCACHE_DIR=/ccache &&
          export CCACHE_NOSTATS=1 &&
          export CCACHE_SLOPPINESS=include_file_mtime &&
          export CC=\"ccache ${CC}\" &&
          apt update -qq && apt install -qqy rmlint &&
          pip3 install -r requirements.txt &&
          python3 generate.py tidy &&
          rm test/test_duplicate_consistency.py &&
          cd test && python3 -m pytest --verbose --junitxml=test-results/pytest/results.xml --numprocesses=auto"
      services:
        - docker
    - name: "KEMs: ARM64 + Clang"
      os: linux
      arch: arm64
      compiler: clang
      script:
        - travis_wait 60 docker run -e CI=true --rm -v ~/.ccache:/ccache -v `pwd`:`pwd` -w `pwd` "pqclean/ci-container:arm64" /bin/bash -c "
          uname -a &&
          export CCACHE_NOSTATS=1 &&
          export CCACHE_DIR=/ccache &&
          export CCACHE_SLOPPINESS=include_file_mtime &&
          export CC=\"ccache ${CC}\" &&
          pip3 install -r requirements.txt &&
          apt update -qq && apt install -qqy rmlint &&
          python3 generate.py tidy &&
          rm test/test_duplicate_consistency.py &&
          cd test && python3 -m pytest --verbose --junitxml=test-results/pytest/results.xml --numprocesses=auto"
      services:
        - docker
    # MacOS builds
    - name: "KEMs: MacOS + Clang"
      os: osx
      osx_image: xcode11.2
      compiler: clang
      before_install:
        - pip3 install -r requirements.txt
      before_script:
        - export CCACHE_NOSTATS=1
        - export CCACHE_SLOPPINESS=include_file_mtime
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      script:
        - python3 generate.py tidy
        - rm test/test_duplicate_consistency.py
        # Use travis-wait to allow slower tests to run
        - "cd test && travis_wait 60 python3 -m pytest --numprocesses=auto"
      addons:
        homebrew:
          packages:
            - astyle
            - ccache
    - name: "KEMs: MacOS + GCC9"
      os: osx
      osx_image: xcode11.2
      compiler: gcc
      addons:
        homebrew:
          packages:
            - astyle
            - ccache
            - gcc@9
      before_install:
        - export CCACHE_NOSTATS=1
        - export CCACHE_SLOPPINESS=include_file_mtime
        - pip3 install -r requirements.txt
        - brew link gcc
        - export PATH="/usr/local/bin:$PATH"
        - export CC="ccache gcc"
        - ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        - gcc --version
      script:
        # Use travis-wait to allow slower tests to run
        - rm test/test_duplicate_consistency.py
        - python3 generate.py tidy
        - "cd test && travis_wait 60 python3 -m pytest --numprocesses=auto"

cache:
  directories:
    - $HOME/Library/Caches/pip
    - $HOME/Library/Caches/Homebrew
    - $HOME/.ccache

before_cache:
  - brew cleanup

#  vim: set ft=yaml ts=2 sw=2 tw=0 et :
