# This Makefile can be used with GNU Make or BSD Make

LIBRARY = libmceliece_clean.lib

OBJECTS = aes256ctr.obj benes.obj bm.obj controlbits.obj decrypt.obj encrypt.obj gf.obj \
	  operations.obj pk_gen.obj root.obj sk_gen.obj synd.obj transpose.obj util.obj

CFLAGS=/nologo /O2 /I ..\..\..\common /W4 /WX

all: $(LIBRARY)

# Make sure objects are recompiled if headers change.
$(OBJECTS): *.h

$(LIBRARY): $(OBJECTS)
	LIB.EXE /NOLOGO /WX /OUT:$@ $**

clean:
	-DEL $(OBJECTS)
	-DEL $(LIBRARY)
