# This Makefile can be used with GNU Make or BSD Make

LIB = lib{{scheme}}_clean.a

SOURCES = aes256ctr.c benes.c bm.c controlbits.c decrypt.c encrypt.c gf.c \
          operations.c pk_gen.c root.c sk_gen.c synd.c transpose.c util.c \
          crypto_int32.c crypto_int16.c crypto_uint16.c crypto_uint32.c crypto_uint64.c
HEADERS = aes256ctr.h api.h benes.h bm.h controlbits.h crypto_hash.h \
          decrypt.h encrypt.h gf.h params.h pk_gen.h root.h operations.h \
          int32_sort.h uint64_sort.h crypto_kem.h namespace.h \
          sk_gen.h synd.h transpose.h util.h \
          crypto_int32.h crypto_int16.h crypto_uint16.h crypto_uint32.h crypto_uint64.h
OBJECTS = aes256ctr.o benes.o bm.o controlbits.o decrypt.o encrypt.o gf.o \
          operations.o pk_gen.o root.o sk_gen.o synd.o transpose.o util.o \
          crypto_int32.o crypto_int16.o crypto_uint16.o crypto_uint32.o crypto_uint64.o

CFLAGS  = -O3 -std=c99 -Wall -Wextra -pedantic -Werror -Wpedantic \
	  -Wredundant-decls -Wcast-align -Wmissing-prototypes \
	  -I../../../common/ $(EXTRAFLAGS)

all: $(LIB)

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS)   -c -o $@ $<

$(LIB): $(OBJECTS)
	$(AR) -r $@ $(OBJECTS)

clean:
	$(RM) $(OBJECTS)
	$(RM) $(LIB)
