
SOURCES = aes256ctr.c benes.c bm.c controlbits.c decrypt.c encrypt.c gf.c operations.c pk_gen.c root.c \
          sk_gen.c synd.c transpose.c util.c
          OBJECTS = aes256ctr.o benes.o bm.o controlbits.o decrypt.o encrypt.o gf.o operations.o pk_gen.o root.o \
                    sk_gen.o synd.o transpose.o util.o

                    CFLAGS  =  -I.. / .. / .. / common / -Wall - Wextra - pedantic - Werror - Wcast - align

                               all:
                               $(OBJECTS)
