name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-14 main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          git submodule update --init
          sudo apt-get install -y astyle valgrind clang-tidy-14 rmlint unifdef
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-14 100
      - name: Setup Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-generate.txt
      - name: Generate implementations
        run: |
          python generate.py tidy
          ./update_duplicate_consistency.sh
      - name: Run tests
        run: |
          cd test
          pytest -nauto -x


# vim : set ts=2 sw=2 et :
