name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
            - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          git submodule update --init
          sudo apt-get install -y astyle valgrind
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate implementations
        run: |
          python generate.py
      - name: Run tests
        run: |
          cd test
          pytest -nauto


# vim : set ts=2 sw=2 et :
