name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: ['gcc', 'clang']
    env:
      CC: ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          git submodule update --init
          sudo apt-get install -y astyle valgrind clang-tidy rmlint unifdef
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Download KAT
        run: ./get_kat.sh
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-generate.txt
      - name: Generate implementations
        run: |
          python generate.py tidy
          ./update_duplicate_consistency.sh
      - name: Run tests
        run: |
          cd test
          pytest -nauto -x


# vim : set ts=2 sw=2 et :
